"""Turning one raw message into headers, text and attachment names.

Two rules hold this module together, and they are the docdex extractor's rules
with mail's own twist:

* **It never raises.** A mailbox is whatever has arrived in it, and what
  arrives is written by strangers: a truncated multipart, a charset that does
  not exist, a Content-Type header with no slash in it, a 40MB base64 blob
  claiming to be `text/plain`. Every one of those is a recorded per-message
  failure, never an exception that ends a sync over the other 499 messages.
* **An honest zero is a result, not a failure.** A message whose only content
  is an image extracts to nothing. Recorded as such, it is never re-fetched;
  recorded as an error, it would be retried forever.

The HTML stripper is a `html.parser` subclass rather than a regex. Mail HTML is
generated by hostile-to-parse tools — nested tags, unclosed tags, `<style>`
blocks the size of the message, entities inside attributes. A regex over that
produces CSS in the corpus; `HTMLParser` handles nesting and character
references by construction, and everything it cannot make sense of it simply
does not emit.
"""
from __future__ import annotations

import email
import email.policy
import email.utils
from dataclasses import dataclass, field
from html.parser import HTMLParser

from . import env_int

DEFAULT_MAX_MESSAGE_KB = 200

# Their content is markup, not prose. Without this, every HTML mail ingests its
# own stylesheet and the recall snippet is a wall of CSS.
_SILENT = frozenset({"script", "style", "head", "title"})

# Tags whose boundaries a reader perceives as a line break.
_BREAKS = frozenset({
    "p", "div", "br", "tr", "li", "h1", "h2", "h3", "h4", "h5", "h6",
    "table", "blockquote", "section", "article", "header", "footer", "pre", "hr",
})

# What travels into `metadata`, in the order a person reads a message.
HEADER_FIELDS = ("subject", "from", "to", "cc", "date", "message_id", "in_reply_to")


def max_message_bytes() -> int:
    """`FIREKEEP_MAILDEX_MAX_MESSAGE_KB`, default 200 (M6)."""
    return env_int("FIREKEEP_MAILDEX_MAX_MESSAGE_KB", DEFAULT_MAX_MESSAGE_KB) * 1024


def truncate(text: str) -> tuple[str, bool]:
    """Cut `text` to the extracted-size cap, returning `(text, truncated)`.

    The cap is a byte budget, so the cut is made on the encoded form and then
    decoded back with `errors="ignore"` — landing mid-codepoint would produce a
    JSON body the server cannot decode.
    """
    limit = max_message_bytes()
    encoded = text.encode("utf-8")
    if len(encoded) <= limit:
        return text, False
    return encoded[:limit].decode("utf-8", "ignore"), True


@dataclass
class Message:
    """One parsed message. `error` and content are NOT exclusive: a message
    whose second part is undecodable still has a first part worth indexing, and
    throwing that away because the tail was broken would lose real mail."""

    headers: dict[str, str] = field(default_factory=dict)
    body: str = ""
    attachments: list[str] = field(default_factory=list)
    error: str | None = None

    @property
    def subject(self) -> str:
        return self.headers.get("subject", "")

    @property
    def message_id(self) -> str:
        return self.headers.get("message_id", "")

    def render(self) -> str:
        """The text that goes into the corpus.

        The headers are prepended as plain lines rather than left only in
        metadata: recall searches CONTENT, and "what did Priya say about the
        invoice" needs the sender's name inside the indexed text to match.
        """
        lines = [
            f"{name.replace('_', '-').title()}: {self.headers[name]}"
            for name in HEADER_FIELDS if self.headers.get(name)
        ]
        body = self.body.strip()
        if self.attachments:
            lines.append(f"Attachments: {', '.join(self.attachments)}")
        if not lines:
            return body
        return "\n".join(lines) + ("\n\n" + body if body else "")


class _Stripper(HTMLParser):
    """HTML in, readable text out. Never raises on malformed markup."""

    def __init__(self):
        # convert_charrefs=True is the default and is what turns `&amp;`,
        # `&#8217;` and `&nbsp;` into characters — including inside deeply
        # nested tags, which is the case a regex stripper gets wrong.
        super().__init__(convert_charrefs=True)
        self._parts: list[str] = []
        # A COUNTER, not a flag: `<style>` inside `<head>` would clear a flag
        # on its closing tag and leak the rest of the head into the output.
        self._muted = 0

    def handle_starttag(self, tag, attrs):
        if tag in _SILENT:
            self._muted += 1
        elif tag in _BREAKS:
            self._parts.append("\n")

    def handle_endtag(self, tag):
        if tag in _SILENT:
            self._muted = max(0, self._muted - 1)
        elif tag in _BREAKS:
            self._parts.append("\n")

    def handle_data(self, data):
        if not self._muted:
            self._parts.append(data)

    def text(self) -> str:
        return _collapse("".join(self._parts))


def strip_html(html: str) -> str:
    """Readable text from a mail HTML part. Never raises."""
    parser = _Stripper()
    try:
        parser.feed(html)
        parser.close()
    except Exception:  # noqa: BLE001 - malformed markup is DATA, not control flow
        pass
    return parser.text()


def _collapse(text: str) -> str:
    """Trim each line, drop runs of blank lines. Mail HTML emits enormous
    amounts of layout whitespace, and a corpus chunk that is 80% newlines
    wastes the embedding budget the real words needed."""
    lines = [line.strip() for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    out: list[str] = []
    for line in lines:
        if line:
            out.append(line)
        elif out and out[-1]:
            out.append("")
    return "\n".join(out).strip()


def parse_message(raw: bytes) -> Message:
    """`(headers, body, attachments, error)` for one raw message. Never raises."""
    msg = Message()
    try:
        parsed = email.message_from_bytes(raw, policy=email.policy.default)
    except Exception as e:  # noqa: BLE001
        # Not even a header block could be recovered. The caller records this
        # against the UID and moves on to the next message.
        msg.error = f"{type(e).__name__}: {e}"[:500]
        return msg

    msg.headers = _headers(parsed)
    try:
        text, html, attachments, part_error = _walk(parsed)
    except Exception as e:  # noqa: BLE001 - a broken part tree, headers survive
        msg.error = f"{type(e).__name__}: {e}"[:500]
        return msg

    msg.attachments = attachments
    msg.error = part_error
    # text/plain wins when both are present: it is what the sender's client
    # wrote for a text reader, and it needs no stripping to be right.
    msg.body = _collapse(text) or strip_html(html)
    return msg


def _headers(parsed) -> dict[str, str]:
    """The seven headers that matter, decoded, never raising.

    A malformed `Subject` with a broken RFC 2047 encoded word raises from the
    policy's header parser on ACCESS, not on parse — so each one is read
    behind its own guard.
    """
    out: dict[str, str] = {}
    for name, key in (("Subject", "subject"), ("From", "from"), ("To", "to"),
                      ("Cc", "cc"), ("Date", "date"),
                      ("Message-ID", "message_id"), ("In-Reply-To", "in_reply_to")):
        try:
            value = parsed.get(name)
        except Exception:  # noqa: BLE001
            continue
        if value is None:
            continue
        try:
            text = str(value).strip()
        except Exception:  # noqa: BLE001
            continue
        if text:
            out[key] = " ".join(text.split())
    return out


def _walk(parsed) -> tuple[str, str, list[str], str | None]:
    """Collect plain text, HTML and attachment NAMES (never their content).

    Attachment bodies are not ingested in round 1 (M6) — filenames only. That
    is a disclosed cap, and it is also the reason a 40MB PDF attachment costs
    this function nothing: the part is never decoded.
    """
    plain: list[str] = []
    html: list[str] = []
    attachments: list[str] = []
    errors: list[str] = []

    for part in _parts(parsed):
        try:
            disposition = (part.get_content_disposition() or "").lower()
            content_type = (part.get_content_type() or "").lower()
        except Exception as e:  # noqa: BLE001
            errors.append(f"unreadable part: {type(e).__name__}")
            continue
        if disposition == "attachment" or content_type not in ("text/plain", "text/html"):
            name = _filename(part)
            if name:
                attachments.append(name)
            continue
        try:
            content = part.get_content()
        except Exception as e:  # noqa: BLE001 - a bad charset, a bad base64 block
            errors.append(f"{content_type}: {type(e).__name__}")
            continue
        if not isinstance(content, str):
            continue
        (plain if content_type == "text/plain" else html).append(content)

    error = "; ".join(errors)[:500] if errors else None
    return "\n\n".join(plain), "\n".join(html), attachments, error


def _parts(parsed):
    try:
        if not parsed.is_multipart():
            return [parsed]
        return list(parsed.walk())
    except Exception:  # noqa: BLE001
        return [parsed]


def _filename(part) -> str:
    try:
        name = part.get_filename()
    except Exception:  # noqa: BLE001
        return ""
    if not name:
        return ""
    # A filename is attacker-controlled text that ends up in metadata a person
    # reads. Newlines out, length bounded — no path separators either, because
    # `../../etc/passwd` as a "filename" should read as nonsense, not as a path.
    cleaned = " ".join(str(name).split()).replace("/", "_").replace("\\", "_")
    return cleaned[:120]
